# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0003_auto_20190304_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(blank=True, default='', null=True)),
                ('Vol_Mua', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Mua', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Ban', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Ban', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Rong', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Rong', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Mua_KL', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Mua_KL', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Ban_KL', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Ban_KL', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_KL_Rong', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Mua_TT', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Mua_TT', models.IntegerField(blank=True, default=0, null=True)),
                ('Vol_Ban_TT', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_Ban_TT', models.IntegerField(blank=True, default=0, null=True)),
                ('Val_TT_Rong', models.IntegerField(blank=True, default=0, null=True)),
                ('Room_NN_hientai', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_Room_NN', models.IntegerField(blank=True, default=0, null=True)),
                ('Phantram_tong_SH_NN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('SH_NN', models.IntegerField(blank=True, default=0, null=True)),
                ('Phantram_SH_NN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
