# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0005_auto_20190304_1437'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdnn',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gdnn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Phantram_SH_NN',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tổng phần trăm SH NN'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Phantram_tong_SH_NN',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tổng phần trăm room NN'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Room_NN_hientai',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Room NN hiện tại'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='SH_NN',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tổng SH NN'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Total_Room_NN',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tổng Room NN'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Ban',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Ban_KL',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán Khớp Lệnh'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Ban_TT',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán TT'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_KL_Rong',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD Khớp Lệnh Ròng'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Mua',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Mua_KL',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua Khớp Lệnh'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Mua_TT',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua TT'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_Rong',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD Ròng'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Val_TT_Rong',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD TT Ròng'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Ban',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Ban_KL',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán Khớp Lệnh'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Ban_TT',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán TT'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Mua',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Mua_KL',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua Khớp Lệnh'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Mua_TT',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua TT'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='Vol_Rong',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KLGD Ròng'),
        ),
        migrations.AlterField(
            model_name='gdnn',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày'),
        ),
    ]
