# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0007_remove_gdnn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdnn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
