# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0008_gdnn_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdnn',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='gdnn',
            name='status',
        ),
    ]
