# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0009_auto_20190305_2353'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdnn',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gdnn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
