# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0010_auto_20190306_0005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdnn',
            managers=[
            ],
        ),
    ]
