# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDNN', '0011_auto_20190306_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='viewed_gdnn',
            field=models.BigIntegerField(default=0),
        ),
    ]
