# Generated by Django 2.1.4 on 2018-12-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vimo', to=settings.AUTH_USER_MODEL),
        ),
    ]
