# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vimo', '0002_auto_20181226_1946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vimo',
            managers=[
            ],
        ),
    ]
