# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vimo', '0003_auto_20190314_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vimo',
            options={'ordering': ('-publish',)},
        ),
    ]
