# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vimo', '0004_auto_20190315_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='viewed_list_Vimo',
            field=models.BigIntegerField(default=0),
        ),
    ]
