# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 06:14
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apublish', models.DateField(default=datetime.date.today)),
                ('Indicator', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('-Apublish',),
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('R_publish', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('R_created', models.DateTimeField(auto_now_add=True)),
                ('R_updated', models.DateTimeField(auto_now=True)),
                ('R_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('viewed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-R_publish',),
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('S_created', models.DateTimeField(auto_now_add=True)),
                ('S_updated', models.DateTimeField(auto_now=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('Withdrawn', 'Withdrawn')], default='draft', max_length=10)),
                ('Symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mã CK')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên Công Ty')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Symbol')),
                ('San', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sàn')),
                ('Website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('So_dien_thoai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('Dia_chi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
                ('Quan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quận/Huyện')),
                ('Tinh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh/Thành')),
                ('Tong_Quan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tổng quan')),
                ('Industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngành')),
                ('SL_CP_Niem_yet', models.BigIntegerField(blank=True, null=True, verbose_name='Số lượng CP Niêm Yết')),
                ('Ty_le_Freeloat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Free-loat')),
                ('Ty_le_SHNN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tỷ lệ SH NN tối đa')),
                ('EnvironmentIndustry', models.IntegerField(default=7)),
                ('W_Envi', models.PositiveIntegerField(default=30)),
                ('Management', models.IntegerField(default=7)),
                ('W_Ma', models.IntegerField(default=15)),
                ('Capital', models.IntegerField(default=7)),
                ('W_Ca', models.IntegerField(default=10)),
                ('Qualify_asset', models.IntegerField(default=7)),
                ('W_Qu_As', models.PositiveIntegerField(default=10)),
                ('Leverage', models.IntegerField(default=7)),
                ('W_Lev', models.PositiveIntegerField(default=10)),
                ('Share', models.IntegerField(default=7)),
                ('W_Share', models.PositiveIntegerField(default=10)),
                ('Perform', models.IntegerField(default=7)),
                ('W_Perform', models.PositiveIntegerField(default=15)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Symbol',),
            },
        ),
        migrations.AddField(
            model_name='recommend',
            name='Stock_chosen',
            field=models.ManyToManyField(through='Stock_detail.Action', to='Stock_detail.StockDetail'),
        ),
        migrations.AddField(
            model_name='action',
            name='DateRecommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock_detail.Recommend'),
        ),
        migrations.AddField(
            model_name='action',
            name='Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock_detail.StockDetail'),
        ),
    ]
