# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
