# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0002_auto_20190318_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='S_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='S_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
