# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0003_auto_20190318_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='S_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('Withdrawn', 'Withdrawn')], default='draft', max_length=10, null=True),
        ),
    ]
