# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 07:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0004_auto_20190318_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='Capital',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='EnvironmentIndustry',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='Leverage',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='Management',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='Perform',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='Qualify_asset',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='Share',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Ca',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Envi',
            field=models.PositiveIntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Lev',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Ma',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Perform',
            field=models.PositiveIntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Qu_As',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='W_Share',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='Symbol'),
        ),
    ]
