# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 09:42
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock_detail', '0005_auto_20190318_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('S_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('S_updated', models.DateTimeField(auto_now=True, null=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('Withdrawn', 'Withdrawn')], default='draft', max_length=10, null=True)),
                ('EnvironmentIndustry', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Envi', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('Management', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Ma', models.IntegerField(blank=True, default=10, null=True)),
                ('Qualify_asset', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Qu_As', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('Leverage', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Lev', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('Top_industry', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Top_industry', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('Perform', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Perform', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('Capital', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Ca', models.IntegerField(blank=True, default=10, null=True)),
                ('Liquidity', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('W_Li', models.IntegerField(blank=True, default=15, null=True)),
                ('Commnent', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Đánh giá DN')),
                ('Indicator', models.IntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('action', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Đề xuất GD')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Stock_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('S_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('S_updated', models.DateTimeField(auto_now=True, null=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('Withdrawn', 'Withdrawn')], default='draft', max_length=10, null=True)),
                ('Symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mã CK')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên Công Ty')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='Symbol')),
                ('San', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sàn')),
                ('Website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('So_dien_thoai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('Dia_chi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
                ('Quan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quận/Huyện')),
                ('Tinh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh/Thành')),
                ('Tong_Quan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tổng quan')),
                ('Industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngành')),
                ('SL_CP_Niem_yet', models.BigIntegerField(blank=True, null=True, verbose_name='Số lượng CP Niêm Yết')),
                ('Ty_le_Freeloat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Free-loat')),
                ('Ty_le_SHNN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tỷ lệ SH NN tối đa')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('Symbol',),
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='DateRecommend',
        ),
        migrations.RemoveField(
            model_name='action',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='author',
        ),
        migrations.AlterField(
            model_name='recommend',
            name='Stock_chosen',
            field=models.ManyToManyField(through='Stock_detail.Estimate', to='Stock_detail.Stock_Detail'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.AddField(
            model_name='estimate',
            name='DateRecommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock_detail.Recommend'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_Com', to='Stock_detail.Stock_Detail'),
        ),
    ]
