# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0006_auto_20190318_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='S_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True),
        ),
    ]
