# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0007_auto_20190318_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='DateRecommend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock_detail.Recommend'),
        ),
    ]
