# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0008_auto_20190318_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='Bookvalue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Book Value'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='EPS',
            field=models.IntegerField(blank=True, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Liquidity_30days',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KL GDTB 30 ngày'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='PB',
            field=models.IntegerField(blank=True, null=True, verbose_name='P/B'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='PE',
            field=models.IntegerField(blank=True, null=True, verbose_name='P/E'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Postion',
            field=models.CharField(blank=True, choices=[('open', 'Mở vị thế GD'), ('Close', 'Đóng vị thế GD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Price_change_20days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 20 ngày'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Price_change_5days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 5 ngày'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Price_change_60days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 60 ngày'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Price_open',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá mở vị thế'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Price_update',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá cập nhật'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Trade',
            field=models.CharField(blank=True, choices=[('Buy', 'Mua'), ('Buy_More', 'Mua Thêm'), ('Hold', 'Nắm  giữ'), ('Take_profit', 'Chốt lời'), ('Cut_loss', 'Cắt lỗ'), ('Sell_partion', 'Bán dần'), ('Sell_all', 'Bán hết')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Capital',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Vốn hóa'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='EnvironmentIndustry',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Mô trường kinh doanh'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Leverage',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Tỷ lệ vay nợ'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Liquidity',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Thanh khoản'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Management',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Quản trị Doanh Nghiệp'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Perform',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Hiệu suất kinh doanh'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Qualify_asset',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Chất lượng tài sản'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Top_industry',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Thứ hạng trong ngành'),
        ),
    ]
