# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0009_auto_20190318_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='Style',
            field=models.CharField(blank=True, choices=[('Longterm', 'Dài hạn'), ('Shorterm', 'Ngắn hạn')], max_length=10, null=True),
        ),
    ]
