# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0010_estimate_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='PB',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='PE',
        ),
    ]
