# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock_detail', '0011_auto_20190318_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_detail',
            name='author',
        ),
        migrations.AddField(
            model_name='estimate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
