# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_detail', '0012_auto_20190318_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='Bookvalue',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Book Value'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='EPS',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Price_open',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Giá mở vị thế'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='Price_update',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Giá cập nhật'),
        ),
    ]
