# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='Indicator',
            field=models.IntegerField(blank=True, default=50, help_text='0-100', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='action',
            field=models.TextField(blank=True, help_text='Cho nhận xét về DN', max_length=2000, null=True, verbose_name='Nhận xét'),
        ),
    ]
