# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0002_auto_20190324_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='author',
        ),
    ]
