# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DexuatGD', '0003_remove_estimate_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
