# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('DexuatGD', '0004_estimate_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Recommend Category',
                'verbose_name_plural': 'Recommend Categorys',
                'ordering': ('title',),
            },
        ),
    ]
