# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0007_auto_20190328_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='nganhdandattt',
            name='Mau',
            field=models.CharField(choices=[('Đỏ', 'red'), ('Vàng', 'yellow'), ('Xanh lá', 'green'), ('Xanh da trời', 'blue')], default='Vàng', max_length=10, null=True),
        ),
    ]
