# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0009_auto_20190329_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nganhdandattt',
            name='Mau',
            field=models.CharField(blank=True, choices=[('red', 'Đỏ'), ('yellow', 'Vàng'), ('green', 'Xanh lá'), ('blue', 'Xanh da trời')], max_length=10, null=True),
        ),
    ]
