# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0011_auto_20190402_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_trade',
            name='DateRecommend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='DexuatGD.Recommend'),
        ),
    ]
