# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0014_auto_20190402_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='Style',
            field=models.CharField(blank=True, choices=[('Dài hạn', 'Dài hạn'), ('Ngắn hạn', 'Ngắn hạn')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='update_trade',
            name='Trade',
            field=models.CharField(blank=True, choices=[('Mua mới', 'Mua mới'), ('Buy_More', 'Mua thêm'), ('Nắm  giữ', 'Nắm  giữ'), ('Chốt lời', 'Chốt lời'), ('Cắt lỗ', 'Cắt lỗ'), ('Bán bớt', 'Bán bớt'), ('Bán hết', 'Bán hết')], max_length=10, null=True),
        ),
    ]
