# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0015_auto_20190402_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Recommends', to='DexuatGD.Recommend_Category'),
        ),
        migrations.AlterField(
            model_name='update_trade',
            name='Trade',
            field=models.CharField(blank=True, choices=[('Mua mới', 'Mua mới'), ('Mua thêm', 'Mua thêm'), ('Nắm  giữ', 'Nắm  giữ'), ('Chốt lời', 'Chốt lời'), ('Cắt lỗ', 'Cắt lỗ'), ('Bán bớt', 'Bán bớt'), ('Bán hết', 'Bán hết')], max_length=10, null=True),
        ),
    ]
