# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0017_auto_20190408_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend_category',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='recommend_category',
            name='site',
        ),
        migrations.RemoveField(
            model_name='recommend_category',
            name='title',
        ),
        migrations.AddField(
            model_name='recommend_category',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommend_category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
