# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('DexuatGD', '0019_auto_20190408_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend_category',
            options={'ordering': ('title',), 'verbose_name': 'Recommend Category', 'verbose_name_plural': 'Recommend Categories'},
        ),
        migrations.RemoveField(
            model_name='recommend_category',
            name='name',
        ),
        migrations.AddField(
            model_name='recommend_category',
            name='site',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommend_category',
            name='title',
            field=models.CharField(default=1, max_length=500, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommend_category',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
    ]
