# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0020_auto_20190408_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_recommend_related_posts_+', to='DexuatGD.Recommend', verbose_name='Related posts'),
        ),
    ]
